apiVersion: v1
kind: Pod
metadata:
  name: bind
  labels:
    name: bind
spec:
  containers:
    - name: bind
      image: lauster/rpi-bind-dns
      ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      emptyDir: {}
